--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Henry12960/BetterJoin
build-by-default: true
branches:
- main
projects:
  BetterJoin:
    path: ""
    icon: "BetterJoin.png"
    libs:
      - src: https://poggit.pmmp.io/ci/Vecnavium/FormsUI/FormsUI
...